import React from 'react';
import { Card, CardContent, Typography } from '@mui/material';
import GradCamSection from '../../../components/GradCamSection';

function GenericExpertAnalysisTab({ aiAssessment, irisGradCamUrl, isIrisGradCamLoading, disease }) {
    return (
        <div className="h-full overflow-y-auto pr-2 space-y-6 pb-8">
            {/* Overview Card */}
            <Card className="border-none shadow-md bg-gradient-to-br from-slate-900 to-slate-800 text-white overflow-hidden">
                <CardContent className="p-6">
                    <div className="flex justify-between items-start">
                        <div>
                            <Typography variant="overline" className="text-slate-300 font-bold tracking-widest">
                                Specialized Visual Analysis
                            </Typography>
                            <Typography variant="h4" className="font-bold mt-1">
                                Expert {disease.charAt(0).toUpperCase() + disease.slice(1)} Review
                            </Typography>
                        </div>
                        <div className="bg-white/20 backdrop-blur-md p-3 rounded-2xl border border-white/30 text-center min-w-[100px]">
                            <Typography className="text-[10px] uppercase font-bold text-slate-100">Confidence Score</Typography>
                            <Typography variant="h5" className="font-black text-white">
                                {Number.isFinite(aiAssessment.confidence) ? Math.round(aiAssessment.confidence) : 0}%
                            </Typography>
                        </div>
                    </div>
                </CardContent>
            </Card>

            <div className="bg-blue-50 rounded-2xl border-2 border-blue-200 p-6">
                <div className="flex items-start gap-4">
                    <div className="bg-blue-600 text-white p-2 rounded-xl">
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                    </div>
                    <div>
                        <h3 className="text-lg font-bold text-blue-900">Expert Insights</h3>
                        <p className="text-sm text-blue-700 mt-1">
                            {aiAssessment.recommendation || "Detailed pathomorphological analysis is currently focusing on iris structural integrity and validation markers."}
                        </p>
                    </div>
                </div>
            </div>

            <GradCamSection 
                gradCamUrl={irisGradCamUrl} 
                isLoading={isIrisGradCamLoading} 
                title="Iris Validation Focus Map"
                description="This visualization highlights the specific regions of the eye scan that the AI model prioritized during its iris validation and structural integrity check."
            />

            {/* Note Section */}
            <div className="bg-gray-100/50 p-6 rounded-2xl border border-gray-200 italic text-center">
                <Typography variant="body2" className="text-gray-500 text-xs">
                    This analysis is generated by a specialized computer vision model. It is intended for referral support and is NOT a definitive medical diagnosis. Professional medical review is mandatory.
                </Typography>
            </div>
        </div>
    );
}

export default GenericExpertAnalysisTab;
